[tool.poetry]
name = "update-counter"
version = "0.1.0"
description = ""
authors = ["SimoneParvizi <simone.parvizi@outlook.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
holidays = "^0.65"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
